### ISSUE TITLE
Add class methods to PayloadRequest model

### ISSUE THREAD

**Issue by ryanflach** [ryanflach/rush-hour-skeleton#13]
These methods should calculate and return:
- Avg. response time for our clients app across all requests
- Max response time across all requests
- Min response time across all requests
- Most frequent request type
- List of all HTTP verbs used

**Comment by ghost** [comment]
David created the most frequent request type and list of all http verbs in the class RequestType, which seems like the most sensible location. The first three methods are in class PayloadRequest, which is appropriate as only that class has access to response time.
